const DATA = [
  {
    id: 1,
    from: '숙대입구',
    ridingTime: '오전 10:40',
    createdAt: '',
    state: '참여중', //회원id에 팟id가 있는지?
    people: 1,
    date: '2023.5.23',
  },
  {
    id: 2,
    from: '숙대입구',
    ridingTime: '오전 10:40',
    createdAt: '',
    state: '참여하기',
    people: 2,
    date: '2023.5.23',
  },
  {
    id: 3,
    from: '숙대입구',
    ridingTime: '오전 10:40',
    createdAt: '',
    state: '참여하기',
    people: 3,
    date: '2023.5.13',
  },
  {
    id: 4,
    from: '숙대입구',
    ridingTime: '오전 10:40',
    createdAt: '',
    state: '참여하기',
    people: 4,
    date: '2023.5.13',
  },
  {
    id: 5,
    from: '효창공원앞',
    ridingTime: '오전 10:40',
    createdAt: '',
    state: '참여하기',
    people: 3,
    date: '2023.5.23',
  },
  {
    id: 6,
    from: '효창공원앞',
    ridingTime: '오전 10:40',
    createdAt: '',
    state: '참여하기',
    people: 4,
    date: '2023.5.23',
  },
  {
    id: 7,
    from: '서울역',
    ridingTime: '오전 10:40',
    createdAt: '',
    state: '참여하기',
    people: 4,
    date: '2023.5.23',
  },
];

export default DATA;
