const DATA = [
  {
    id: 1,
    route: '숙대입구',
    ridingTime: '오전 10:40',
    createdAt: '',
    state: '참여중',
    people: 1,
  },
  {
    id: 2,
    route: '숙대입구',
    ridingTime: '오전 10:40',
    createdAt: '',
    state: '참여하기',
    people: 2,
  },
  {
    id: 3,
    route: '숙대입구',
    ridingTime: '오전 10:40',
    createdAt: '',
    state: '참여하기',
    people: 3,
  },
  {
    id: 4,
    route: '숙대입구',
    ridingTime: '오전 10:40',
    createdAt: '',
    state: '참여하기',
    people: 4,
  },
  {
    id: 5,
    route: '효창공원앞',
    ridingTime: '오전 10:40',
    createdAt: '',
    state: '참여하기',
    people: 4,
  },
  {
    id: 6,
    route: '효창공원앞',
    ridingTime: '오전 10:40',
    createdAt: '',
    state: '참여하기',
    people: 4,
  },
  {
    id: 7,
    route: '서울역',
    ridingTime: '오전 10:40',
    createdAt: '',
    state: '참여하기',
    people: 4,
  },
];

export default DATA;
